# https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601
on:
  push:
    branches:
      - master

name: Release and upload apps

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.version_bump.outputs.new_tag }}
#           release_name: Release ${{ steps.version_bump.outputs.new_tag }}
#           draft: false
#           prerelease: false
      - name: Compress apps
        run: |
          cd ./apps;
          for f in */; do
            echo "Zipping ${f}...";
            zip -qr "${f%/*}" "${f}"*;
          done
          cd -;
      - name: Create release and upload zipped apps
        run: |
          cd ./apps;
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF}"
          hub release create "${assets[@]}" -m "Release ${tag_name}" "$tag_name"
          cd -;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ steps.version_bump.outputs.new_tag }}
